[2024-01-08T11:17:52.786+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_dag.wait_for_add_file manual__2024-01-08T10:17:50.686017+00:00 [queued]>
[2024-01-08T11:17:52.790+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_dag.wait_for_add_file manual__2024-01-08T10:17:50.686017+00:00 [queued]>
[2024-01-08T11:17:52.790+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-08T11:17:52.803+0100] {taskinstance.py:1382} INFO - Executing <Task(SqlSensor): wait_for_add_file> on 2024-01-08 10:17:50.686017+00:00
[2024-01-08T11:17:52.806+0100] {standard_task_runner.py:57} INFO - Started process 82994 to run task
[2024-01-08T11:17:52.808+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_dag', 'wait_for_add_file', 'manual__2024-01-08T10:17:50.686017+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpka5fnm9w']
[2024-01-08T11:17:52.810+0100] {standard_task_runner.py:85} INFO - Job 13: Subtask wait_for_add_file
[2024-01-08T11:17:52.836+0100] {task_command.py:416} INFO - Running <TaskInstance: load_data_dag.wait_for_add_file manual__2024-01-08T10:17:50.686017+00:00 [running]> on host DESKTOP-9ILQL7F.
[2024-01-08T11:17:52.876+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data_dag' AIRFLOW_CTX_TASK_ID='wait_for_add_file' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T10:17:50.686017+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-08T10:17:50.686017+00:00'
[2024-01-08T11:17:52.880+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:17:53.029+0100] {sql.py:95} INFO - Poking: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T); (with parameters None)
[2024-01-08T11:17:53.033+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:17:53.034+0100] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.10.12, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-01-08T11:17:53.034+0100] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-01-08T11:17:53.637+0100] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-01-08T11:17:53.747+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:17:53.747+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:17:53.747+0100] {sql.py:450} INFO - Running statement: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T);, parameters: None
[2024-01-08T11:17:53.747+0100] {cursor.py:1028} INFO - query: [SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOU...]
[2024-01-08T11:17:54.002+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:17:54.002+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:17:54.002+0100] {sql.py:459} INFO - Rows affected: 1
[2024-01-08T11:17:54.002+0100] {snowflake.py:400} INFO - Rows affected: 1
[2024-01-08T11:17:54.002+0100] {snowflake.py:401} INFO - Snowflake query id: 01b187a9-0000-50da-0000-00003fbda3b1
[2024-01-08T11:17:54.003+0100] {cursor.py:1028} INFO - query: [COMMIT]
[2024-01-08T11:17:54.092+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:17:54.092+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:17:54.092+0100] {connection.py:718} INFO - closed
[2024-01-08T11:17:54.141+0100] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-01-08T11:18:04.234+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:18:04.234+0100] {sql.py:95} INFO - Poking: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T); (with parameters None)
[2024-01-08T11:18:04.235+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:18:04.236+0100] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.10.12, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-01-08T11:18:04.236+0100] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-01-08T11:18:04.663+0100] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-01-08T11:18:04.772+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:04.772+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:04.773+0100] {sql.py:450} INFO - Running statement: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T);, parameters: None
[2024-01-08T11:18:04.773+0100] {cursor.py:1028} INFO - query: [SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOU...]
[2024-01-08T11:18:05.166+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:05.166+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:05.166+0100] {sql.py:459} INFO - Rows affected: 1
[2024-01-08T11:18:05.166+0100] {snowflake.py:400} INFO - Rows affected: 1
[2024-01-08T11:18:05.167+0100] {snowflake.py:401} INFO - Snowflake query id: 01b187aa-0000-50db-0000-00003fbdb14d
[2024-01-08T11:18:05.167+0100] {cursor.py:1028} INFO - query: [COMMIT]
[2024-01-08T11:18:05.257+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:05.258+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:05.258+0100] {connection.py:718} INFO - closed
[2024-01-08T11:18:05.306+0100] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-01-08T11:18:15.392+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:18:15.392+0100] {sql.py:95} INFO - Poking: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T); (with parameters None)
[2024-01-08T11:18:15.393+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:18:15.394+0100] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.10.12, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-01-08T11:18:15.394+0100] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-01-08T11:18:15.984+0100] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-01-08T11:18:16.149+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:16.150+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:16.150+0100] {sql.py:450} INFO - Running statement: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T);, parameters: None
[2024-01-08T11:18:16.150+0100] {cursor.py:1028} INFO - query: [SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOU...]
[2024-01-08T11:18:16.444+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:16.444+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:16.444+0100] {sql.py:459} INFO - Rows affected: 1
[2024-01-08T11:18:16.444+0100] {snowflake.py:400} INFO - Rows affected: 1
[2024-01-08T11:18:16.444+0100] {snowflake.py:401} INFO - Snowflake query id: 01b187aa-0000-50da-0000-00003fbda3c9
[2024-01-08T11:18:16.445+0100] {cursor.py:1028} INFO - query: [COMMIT]
[2024-01-08T11:18:16.560+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:16.561+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:16.561+0100] {connection.py:718} INFO - closed
[2024-01-08T11:18:16.637+0100] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-01-08T11:18:26.766+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:18:26.767+0100] {sql.py:95} INFO - Poking: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T); (with parameters None)
[2024-01-08T11:18:26.768+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:18:26.768+0100] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.10.12, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-01-08T11:18:26.768+0100] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-01-08T11:18:27.790+0100] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-01-08T11:18:27.890+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:27.890+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:27.890+0100] {sql.py:450} INFO - Running statement: SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOURCE_CSV_STAGE T);, parameters: None
[2024-01-08T11:18:27.891+0100] {cursor.py:1028} INFO - query: [SELECT EXISTS(SELECT DISTINCT  METADATA$FILENAME FROM @TASK_8.STAGING_SCHEMA.SOU...]
[2024-01-08T11:18:28.273+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:28.273+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:28.273+0100] {sql.py:459} INFO - Rows affected: 1
[2024-01-08T11:18:28.273+0100] {snowflake.py:400} INFO - Rows affected: 1
[2024-01-08T11:18:28.273+0100] {snowflake.py:401} INFO - Snowflake query id: 01b187aa-0000-50da-0000-00003fbda3dd
[2024-01-08T11:18:28.273+0100] {cursor.py:1028} INFO - query: [COMMIT]
[2024-01-08T11:18:28.358+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:18:28.358+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:18:28.358+0100] {connection.py:718} INFO - closed
[2024-01-08T11:18:28.407+0100] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-01-08T11:18:28.473+0100] {base.py:287} INFO - Success criteria met. Exiting.
[2024-01-08T11:18:28.475+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_data_dag, task_id=wait_for_add_file, execution_date=20240108T101750, start_date=20240108T101752, end_date=20240108T101828
[2024-01-08T11:18:28.520+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-08T11:18:28.531+0100] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
