[2024-01-08T11:27:46.731+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_dag.load_data manual__2024-01-08T10:27:41.478151+00:00 [queued]>
[2024-01-08T11:27:46.736+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_dag.load_data manual__2024-01-08T10:27:41.478151+00:00 [queued]>
[2024-01-08T11:27:46.736+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-08T11:27:46.748+0100] {taskinstance.py:1382} INFO - Executing <Task(SnowflakeOperator): load_data> on 2024-01-08 10:27:41.478151+00:00
[2024-01-08T11:27:46.751+0100] {standard_task_runner.py:57} INFO - Started process 83240 to run task
[2024-01-08T11:27:46.753+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_dag', 'load_data', 'manual__2024-01-08T10:27:41.478151+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpmkxbwfo7']
[2024-01-08T11:27:46.754+0100] {standard_task_runner.py:85} INFO - Job 20: Subtask load_data
[2024-01-08T11:27:46.788+0100] {task_command.py:416} INFO - Running <TaskInstance: load_data_dag.load_data manual__2024-01-08T10:27:41.478151+00:00 [running]> on host DESKTOP-9ILQL7F.
[2024-01-08T11:27:46.826+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T10:27:41.478151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-08T10:27:41.478151+00:00'
[2024-01-08T11:27:46.827+0100] {sql.py:276} INFO - Executing: CALL TASK_8.STAGING_SCHEMA.LOAD_SOURCE_DATA_TO_STAGING()
[2024-01-08T11:27:46.830+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:27:46.974+0100] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-01-08T11:27:46.974+0100] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.10.12, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-01-08T11:27:46.975+0100] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-01-08T11:27:47.400+0100] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=True]
[2024-01-08T11:27:47.553+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:27:47.553+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:27:47.554+0100] {sql.py:450} INFO - Running statement: CALL TASK_8.STAGING_SCHEMA.LOAD_SOURCE_DATA_TO_STAGING(), parameters: None
[2024-01-08T11:27:47.554+0100] {cursor.py:1028} INFO - query: [CALL TASK_8.STAGING_SCHEMA.LOAD_SOURCE_DATA_TO_STAGING()]
[2024-01-08T11:27:51.328+0100] {cursor.py:1041} INFO - query execution done
[2024-01-08T11:27:51.328+0100] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-01-08T11:27:51.328+0100] {sql.py:459} INFO - Rows affected: 1
[2024-01-08T11:27:51.328+0100] {snowflake.py:400} INFO - Rows affected: 1
[2024-01-08T11:27:51.328+0100] {snowflake.py:401} INFO - Snowflake query id: 01b187b3-0000-50db-0000-00003fbdb1e9
[2024-01-08T11:27:51.328+0100] {connection.py:718} INFO - closed
[2024-01-08T11:27:51.404+0100] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-01-08T11:27:51.539+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_data_dag, task_id=load_data, execution_date=20240108T102741, start_date=20240108T102746, end_date=20240108T102751
[2024-01-08T11:27:51.602+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-08T11:27:51.610+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
